name: redstone_mapper_pg
version: 0.2.0-beta.2
author: Luiz Mineo <luiz.mineo@gmail.com>
description: PostgreSQL extension for redstone_mapper
homepage: http://redstonedart.org
environment:
  sdk: '>=1.9.0-dev.9.1 <2.0.0'
dependencies:
  redstone:
    git: https://github.com/redstone-dart/redstone.git
  redstone_mapper:
    git: https://github.com/redstone-dart/redstone_mapper.git
  postgresql: ^0.3.1+1
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
  mock: '>=0.11.0+1 <0.12.0'
